baseURL = 'https://bkl-dev.com/'
languageCode = 'en-us'
title = 'Development Site'

[build]
  [build.buildStats]
    enable = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

